Moving commit_notifications to inside notifications
The reason for the move is that the `notification` service folder would import from `commit_notification` service folder, and the `commit_notification` service folder would import from something inside the `notification` service folder.

It was not a big deal. But when I tried to run `isort` on it, the new import order made that import start being circular.

```
../lib/python3.9/site-packages/py/_path/local.py:704: in pyimport
    __import__(modname)
services/notification/__init__.py:18: in <module>
    from services.commit_notifications import (
services/commit_notifications.py:5: in <module>
    from services.notification.notifiers.base import (
services/notification/__init__.py:18: in <module>
    from services.commit_notifications import (
E   ImportError: cannot import name 'create_or_update_commit_notification_from_notification_result' from partially initialized module 'services.commit_notifications' (most likely due to a circular import) (/Users/thiagorramos/Projects/workerenv/worker/services/commit_notifications.py)
```


And I believe something that is safe only when the import order is right might be dangerous.

One of the imports was only for the purpose of typing.

We could remove the typing, or change the function to use something different, but looking at the folders, it made sense that `commit_notifications` belonged inside `notifications`