Removing None from comparison
`
Caused by

```
Traceback (most recent call last):
  File "/worker/services/notification/__init__.py", line 186, in notify_individual_notifier
    res = await notifier.notify(comparison)
  File "/worker/services/notification/notifiers/checks/checks_with_fallback.py", line 50, in notify
    res = await self._checks_notifier.notify(comparison)
  File "/worker/services/notification/notifiers/checks/base.py", line 169, in notify
    payload = await self.build_payload(filtered_comparison)
  File "/worker/services/notification/notifiers/checks/project.py", line 65, in build_payload
    message = await self.get_message(comparison, settings_to_be_used)
  File "/worker/services/notification/notifiers/checks/project.py", line 21, in get_message
    return await self.create_message(comparison, pull_dict, yaml_comment_settings)
  File "/worker/services/notification/notifiers/mixins/message.py", line 157, in create_message
    changes = await comparison.get_changes()
  File "/worker/services/comparison/__init__.py", line 110, in get_changes
    self._changes = get_changes(
  File "/usr/local/lib/python3.8/site-packages/statsd/client/timer.py", line 38, in _wrapped
    return f(*args, **kwargs)
  File "/worker/services/comparison/changes.py", line 157, in get_changes
    lines = list(
  File "/worker/services/comparison/changes.py", line 218, in iter_changed_lines
    max(
TypeError: '>' not supported between instances of 'int' and 'NoneType'
```