Dealing with some cases where some None values appear
Sometimes `diff_json` and `diff` are unexpectedly None. We need to add handling around them

On the first case, it's only a matter of checking for None

On the second case, the logic is that if the base file is missing and there is no diff of it, then it is probably a file that is "new". It is weird that the previous logic did not mark it as such already (it wouldn't have gotten to this point if it did). so we are logging to find out why this case happens. And we are also marking it as such

The stacktrace is:

https://sentry.io/organizations/codecov/issues/2682272764/events/0595d426f5794ed483dc8338888ca417/?project=4165036&query=is%3Aunresolved+%27NoneType%27+object+has+no+attribute+%27get%27&statsPeriod=14d

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner
    return f(*args, **kwargs)
  File "/worker/tasks/base.py", line 54, in run
    return asyncio.run(self.run_async(db_session, *args, **kwargs))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/worker/tasks/sync_pull.py", line 69, in run_async
    return await self.run_async_within_lock(
  File "/worker/tasks/sync_pull.py", line 181, in run_async_within_lock
    await self.update_pull_from_reports(
  File "/worker/tasks/sync_pull.py", line 247, in update_pull_from_reports
    changes = get_changes(base_report, head_report, diff)
  File "/usr/local/lib/python3.8/site-packages/statsd/client/timer.py", line 38, in _wrapped
    return f(*args, **kwargs)
  File "/worker/services/comparison/changes.py", line 145, in get_changes
    if diff.get("type") == "new":
AttributeError: 'NoneType' object has no attribute 'get'
```